Add repository
L1mple/TODO_list pull request #12
Opened 2022-11-04 12:52 UTC by L1mple

2022-11-07 10:04 UTC, katunilya reviewed
![image](https://user-images.githubusercontent.com/40162026/200279854-9989840c-8555-4ac0-abaa-f85ea19f3c91.png)

В общем какая логика

Есть условный `domain` в котором лежат
- domain models
- domain logic
- domain abstractions (`TaskRepository` - `abc.ABC`/`typing.Protocol`)

А есть service в котором лежат реализации, например

`app/service/mongo/task.py` - `MongoTaskRepository`

Если нам нужны более общие абстракции, то у нас появляется shared kernel для domain, в котором например лежит generic `Repository`, который реализует базовый CRUD

```py
from typing import Generic, Protocol, TypeVar

from pydantic import BaseModel

TUID = TypeVar("TUID")


class Entity(Generic[TUID], BaseModel):

    uid: TUID | None


TEntity = TypeVar("TEntity", bound=Entity)


class Repository(Protocol[TEntity, TUID]):
    def create_one(self, entity: TEntity) -> TUID:
        ...

    def create_many(self, entities: list[TEntity]) -> list[TUID]:
        ...

    def get_one_by_uid(self, uid: TUID) -> TEntity | None:
        ...

    def get_many(self, page: int = 0, per_page: int = 10) -> list[TEntity]:
        ...

    def delete_one_by_uid(self, uid: TUID) -> None:
        ...

    def replace_one(self, entity: TEntity) -> None:
        ...

```

Далее от этого Repository уже в subdomain task мы наследуемся в `TaskRepository` у которого могут быть уже свои дополнительные методы.

А в service у нас появляется реализация абстрактного `Repository` - `MongoRepository`.

Далее когда мы хотим реализовать `MongoTaskRepository` мы наследуемся от `TaskRepository` (чтобы получить кастомные методы) и `MongoRepository` (чтобы автоматически реализовать не кастомные методы)

Получается такая диаграмма наследования:

![image](https://user-images.githubusercontent.com/40162026/200282465-052297b4-7eb9-4216-ba0e-c7312c859694.png)

Вот к этому кажется ты идешь

2022-11-07 10:04 UTC, katunilya commented on todo/services/tasks.py
> +    async def get_user_by_id(self, task_id: ObjectId) -> Task:
domain не должен знать про `ObjectId` тк БД может поменяться и идентификатором может быть `int`, `guid`

Я как правило завожу type alias для uid - str (`TaskUID = str`), тк они позволяют проверять уникальность, а уже в service layer перевожу в конкретные форматы

2022-11-08 23:42 UTC, L1mple commented
На endpointы можно пока не смотреть, я их для дебага репозитория написал

2022-11-16 13:11 UTC, katunilya requested changes

2022-11-16 13:11 UTC, katunilya commented on todo/api/endpoints.py
> +    return await repository.delete_one_by_id(uid=PyObjectId(task_id))
А почему мы передаем вместо `str` `PyObjectId`?

У нас же интерфейс строку просит

2022-11-16 13:11 UTC, katunilya commented on setup.cfg
> +inline-quotes = ""
тут только одна "

2022-11-16 13:11 UTC, katunilya commented on docker-compose.yaml
> +      - config\docker.env
такие пути не работают на unix

2022-11-25 07:20 UTC, merged